<?php

namespace App\Http\Controllers;

use App\Models\Initiative;
use App\Models\Volunteer;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\File;
use Spipu\Html2Pdf\Html2Pdf;

class PDFController extends Controller
{

    protected function postPDF($mobile,$id){
        $v = Volunteer::query()->where('id',$mobile)->first();
        $i = DB::table('initiative_volunteer')->where('id',$id)->first();
        $ii = Initiative::query()->where('id',$i->initiative_id)->first();

        ob_start();
        $nameVol = $v->name;
        $hour = $i->hours;
        $namIni = $ii->name;
        $content = view('pdf',['name'=>$nameVol, 'hours'=>$hour, 'namIni'=>$namIni])->render();
        $html2pdf_path = base_path() . '\vendor\spipu\html2pdf\src\html2pdf.php';
        File::requireOnce($html2pdf_path);

        try {
            $html2pdf = new HTML2PDF('L', 'A4', 'en');//, true, 'UTF-8', array(25.4, 20.4, 25.4, 20.4));
            $lg = Array();
            $lg['a_meta_charset'] = 'UTF-8';
            $lg['a_meta_dir'] = 'rtl';
            $lg['a_meta_language'] = 'fa';
            $lg['w_page'] = 'page';
            // set some language-dependent strings (optional)
            $html2pdf->pdf->setLanguageArray($lg);
//
//            $add = $html2pdf->addFont('cairo','R',base_path('fonts/Cairo-Regular.ttf'));
//            $html2pdf->pdf->SetFont('dejavusans ', '', 12);
            $html2pdf->setDefaultFont('aealarabiya');
//            $font =
//            $html2pdf->pdf->SetTitle('HTML2PDF Sample');
            $html2pdf->WriteHTML($content);
            $html2pdf->Output('example.pdf');

            ob_flush();
            ob_end_clean();
        }
        catch (\Exception $e) {
            echo $e;
            exit;
        }
        $pdf= $html2pdf->Output('', 'S');
        return response($pdf)
            ->header('Content-Type', 'application/pdf')
            ->header('Content-Length', strlen($pdf))
            ->header('Content-Disposition', 'inline','filename="example.pdf"');
    }


    protected function makePDF(){
        ob_start();
        $name = "عبده حسين حاوي";
        $namIni = "مليون متطوع تقني";
        $hour = "30";
        $content = view('pdf',['name'=>$name, 'hours'=>$hour,'namIni'=>$namIni])->render();
        $html2pdf_path = base_path() . '\vendor\spipu\html2pdf\src\html2pdf.php';
        File::requireOnce($html2pdf_path);

        try {
            $html2pdf = new HTML2PDF('L', 'A4', 'en');//, true, 'UTF-8', array(25.4, 20.4, 25.4, 20.4));
            $lg = Array();
            $lg['a_meta_charset'] = 'UTF-8';
            $lg['a_meta_dir'] = 'rtl';
            $lg['a_meta_language'] = 'fa';
            $lg['w_page'] = 'page';
            // set some language-dependent strings (optional)
            $html2pdf->pdf->setLanguageArray($lg);
//            $add = $html2pdf->addFont('cairo','R',base_path('fonts/Cairo-Regular.ttf'));
//            $html2pdf->pdf->SetFont('dejavusans ', '', 12);
            $html2pdf->setDefaultFont('aealarabiya');
//            $font =
//            $html2pdf->pdf->SetTitle('HTML2PDF Sample');
            $html2pdf->WriteHTML($content);
            $html2pdf->Output('example.pdf');

            ob_flush();
            ob_end_clean();
        }
        catch (\Exception $e) {
            echo $e;
            exit;
        }
        $pdf= $html2pdf->Output('', 'S');
        return response($pdf)
            ->header('Content-Type', 'application/pdf')
            ->header('Content-Length', strlen($pdf))
            ->header('Content-Disposition', 'inline','filename="example.pdf"');
    }

    protected function send(){
        // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
        $ch = curl_init();
        $url = 'https://fcm.googleapis.com/v1/projects/myproject-b5ae1/messages:send';
        $body = array(

        );

        curl_setopt($ch, CURLOPT_URL, $url);
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, "{\n\"message\":{\n   \"notification\":{\n     \"title\":\"FCM Message\",\n     \"body\":\"This is an FCM Message\"\n   },\n   \"token\":\"bk3RNwTe3H0:CI2k_HHwgIpoDKCIZvvDMExUdFQ3P1...\"\n}}");

        $headers = array();
        $headers[] = 'Authorization: Bearer ya29.ElqKBGN2Ri_Uz...HnS_uNreA';
        $headers[] = 'Content-Type: application/json';
        curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

        $result = curl_exec($ch);
        if (curl_errno($ch)) {
            echo 'Error:' . curl_error($ch);
        }
        curl_close($ch);

    }
}
